# Generated by Django 5.2.6 on 2025-09-08 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(help_text='Nombre de la calle', max_length=200)),
                ('numero', models.CharField(help_text='Número de la dirección', max_length=10)),
                ('comuna', models.CharField(help_text='Comuna', max_length=100)),
                ('ciudad', models.CharField(help_text='Ciudad', max_length=100)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del cliente', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('direccion', models.ForeignKey(help_text='Dirección del cliente', on_delete=django.db.models.deletion.CASCADE, to='ventas.direccion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del proveedor', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=100)),
                ('telefono', models.CharField(help_text='Teléfono del proveedor', max_length=15)),
                ('web', models.URLField(blank=True, help_text='Página web del proveedor')),
                ('direccion', models.ForeignKey(help_text='Dirección del proveedor', on_delete=django.db.models.deletion.CASCADE, to='ventas.direccion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio actual del producto', max_digits=10)),
                ('stock', models.IntegerField(help_text='Cantidad disponible en inventario')),
                ('categoria', models.ForeignKey(help_text='Categoría del producto', on_delete=django.db.models.deletion.CASCADE, to='ventas.categoria')),
                ('proveedores', models.ManyToManyField(help_text='Proveedores que suministran este producto', to='ventas.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='TelefonoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de teléfono', max_length=15)),
                ('cliente', models.ForeignKey(help_text='Cliente propietario del teléfono', on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
            options={
                'verbose_name': 'Teléfono de Cliente',
                'verbose_name_plural': 'Teléfonos de Clientes',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número único de factura', max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la venta')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado en porcentaje', max_digits=5)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total de la venta', max_digits=10)),
                ('cliente', models.ForeignKey(help_text='Cliente que realiza la compra', on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_momento', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento de la venta', max_digits=10)),
                ('cantidad', models.IntegerField(help_text='Cantidad de productos vendidos')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total de esta línea (precio_momento * cantidad)', max_digits=10)),
                ('producto', models.ForeignKey(help_text='Producto vendido', on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('venta', models.ForeignKey(help_text='Venta a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
    ]
