# Generated by Django 5.2.6 on 2025-09-08 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(help_text='Producto vendido', on_delete=django.db.models.deletion.PROTECT, to='ventas.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría del producto', on_delete=django.db.models.deletion.PROTECT, to='ventas.categoria'),
        ),
    ]
